### PR TITLE
[fix][s]: Split tag_string into separate tags - Fixes #8

### LINKED ISSUE #8: Multiple Tags are Combined on the Dataset Page
Where a dataset has multiple keyword tags these are displayed correctly on the edit form as separate tags, but combined to one 'lozenge' the [view](https://data.pkc.gov.uk/dataset/house-prices-by-intermediate-zone).

### PR DESCRIPTION
**Pull request by mpolidori**
I have run into the same issue that #8 mentions. I'm seeing multiple tags concatenated (only for private datasets, not sure why on that). Looking at the function that's supposed to be separating them, it appears to only do the equivalent of this:

```
def _tag_string_to_list(self, tag_string):
    return [{'name': tag_string, 'state': 'active'}]
```

### CODE REVIEW

**Comment by mpolidori** [comment]
@zelima Still failing with an error related to Solr and a test. I'm looking into it.

**Comment by mpolidori** [comment]
@zelima I've been trying a lot of different things. I can't seem to get Solr/Jetty running. Most of the extensions I'm looking at are failing (probably for the same reason). I have found a few passing, and I've been copying/changing to those configurations, but I'm not making much progress.

**Comment by mpolidori** [comment]
@zelima Travis is now passing.

**Comment by zelima** [comment]
@mpolidori thanks

**Pull request merged**
